name: Generate Auto Subtitle TikTok Style

on:
  workflow_dispatch:
    inputs:
      video_url:
        description: 'Link Direct Download Video'
        required: true
      model_type:
        description: 'Model Whisper (tiny/base/small)'
        required: true
        default: 'small'

jobs:
  render:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # --- BAGIAN CACHE MULAI DISINI ---
      - name: Cache Python Packages
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install System & Register Font
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          sudo mkdir -p /usr/local/share/fonts/custom
          sudo cp Montserrat-Black.ttf /usr/local/share/fonts/custom/
          sudo fc-cache -fv

      - name: Install Python Libraries
        run: |
          python -m pip install --upgrade pip
          # Kalau cache ada, proses ini bakal instan
          pip install ffmpeg-python openai-whisper
          pip install -e .

      - name: Download Video
        run: |
          curl -L "${{ github.event.inputs.video_url }}" -o input_video.mp4

      - name: Run Auto Subtitle
        run: |
          auto_subtitle "input_video.mp4" --model ${{ github.event.inputs.model_type }} --output_dir ./output --output_srt True

      - name: Upload Result
        uses: actions/upload-artifact@v4
        with:
          name: video-tiktok-hasil
          path: output/
